version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./config/production.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
      - ./dist:/usr/share/nginx/html/dist
    ports:
      - "8023:80"
